<?php
global $dttheme_social_bookmarks; // Used in Blog single & page tab in BPanel
$dttheme_social_bookmarks = array(array(
							"id"=>		"googleplus",
							"label"=>	__("Show Google+ One",'spalab'),
							"options"=>	array(
								"standard"=>__("Standard",'spalab'),
								"small"=>__("Small",'spalab'),
								"medium"=>__("Medium",'spalab'),
								"tall"=>__("Tall",'spalab')),
							"lang"=>array(
								"ar" => __( "Arabic", 'spalab' ),
								"bn" => __( "Bengali", 'spalab' ),
								"bg" => __( "Bulgarian", 'spalab' ),
								"ca" => __( "Catalan", 'spalab' ),
								"zh" => __( "Chinese", 'spalab' ),
								"zh_CN" => __( "Chinese (China)", 'spalab' ),
								"zh_HK" => __( "Chinese (Hong Kong)", 'spalab' ),
								"zh_TW" => __( "Chinese (Taiwan)", 'spalab' ),
								"hr" => __( "Croation", 'spalab' ),
								"cs" => __( "Czech", 'spalab' ),
								"da" => __( "Danish", 'spalab' ),
								"nl" => __( "Dutch", 'spalab' ),
								"en_IN" => __( "English (India)", 'spalab' ),
								"en_IE" => __( "English (Ireland)", 'spalab' ),
								"en_SG" => __( "English (Singapore)", 'spalab' ),
								"en_ZA" => __( "English (South Africa)", 'spalab' ),
								"en_GB" => __( "English (United Kingdom)", 'spalab' ),
								"fil" => __( "Filipino", 'spalab' ),
								"fi" => __( "Finnish", 'spalab' ),
								"fr" => __( "French", 'spalab' ),
								"de" => __( "German", 'spalab' ),
								"de_CH" => __( "German (Switzerland)", 'spalab' ),
								"el" => __( "Greek", 'spalab' ),
								"gu" => __( "Gujarati", 'spalab' ),
								"iw" => __( "Hebrew", 'spalab' ),
								"hi" => __( "Hindi", 'spalab' ),
								"hu" => __( "Hungarian", 'spalab' ),
								"in" => __( "Indonesian", 'spalab' ),
								"it" => __( "Italian", 'spalab' ),
								"ja" => __( "Japanese", 'spalab' ),
								"kn" => __( "Kannada", 'spalab' ),
								"ko" => __( "Korean", 'spalab' ),
								"lv" => __( "Latvian", 'spalab' ),
								"ln" => __( "Lingala", 'spalab' ),
								"lt" => __( "Lithuanian", 'spalab' ),
								"ms" => __( "Malay", 'spalab' ),
								"ml" => __( "Malayalam", 'spalab' ),
								"mr" => __( "Marathi", 'spalab' ),
								"no" => __( "Norwegian", 'spalab' ),
								"or" => __( "Oriya", 'spalab' ),
								"fa" => __( "Persian", 'spalab' ),
								"pl" => __( "Polish", 'spalab' ),
								"pt_BR" => __( "Portugese (Brazil)", 'spalab' ),
								"pt_PT" => __( "Portugese (Portugal)", 'spalab' ),
								"ro" => __( "Romanian", 'spalab' ),
								"ru" => __( "Russian", 'spalab' ),
								"sr" => __( "Serbian", 'spalab' ),
								"sk" => __( "Slovak", 'spalab' ),
								"sl" => __( "Slovenian", 'spalab' ),
								"es" => __( "Spanish", 'spalab' ),
								"sv" => __( "Swedish", 'spalab' ),
								"gsw" => __( "Swiss German", 'spalab' ),
								"ta" => __( "Tamil", 'spalab' ),
								"te" => __( "Telugu", 'spalab' ),
								"th" => __( "Thai", 'spalab' ),
								"tr" => __( "Turkish", 'spalab' ),
								"uk" => __( "Ukranian", 'spalab' ),
								"vi" => __( "Vietnamese", 'spalab' ))
						),array(
							"id"=>		"fb_like",
							"label"=>	__("Show Facebook like",'spalab'),
							"options"=>	array(
								"standard"=>__("Standard",'spalab'),
								"box_count" =>__("Box Count",'spalab'),
								"button_count" =>__("Button Count",'spalab')),
							"color-scheme"=>array("dark","light")
						),array(
							"id"=>		"digg",
							"label"=>	__("Show Digg",'spalab'),
							"options"=>	array(
									"DiggWide"=>__("Wide",'spalab'),
									"DiggMedium"=>__("Medium",'spalab'),
									"DiggCompact"=>__("Compact",'spalab'),
									"DiggIcon"=>__("Icon",'spalab'))
						),array(
							"id"=>		"stumbleupon",
							"label"=>	__("Show Stumbleupon",'spalab'),
							"options"=>	array(
										"1"=>__("style1",'spalab'),
										"2"=>__("style2",'spalab'),
										"3"=>__("style3",'spalab'),
										"4"=>__("style4",'spalab'),
										"5"=>__("style5",'spalab'),
										"6"=>__("style6",'spalab'))
						),array("id"=>		"linkedin",
							"label"=>	__("Show LinkedIn",'spalab'),
							"options"=>	array("1"=>"style1","2"=>"style2","3"=>"style3")
						),array(
							"id"=>		"pintrest",
							"label"=>	__("Show Pintrest",'spalab'),
							"options"=>	array("none" =>__("None",'spalab'),"vertical" =>__("Vertical",'spalab'),"horizontal"=>__("Horizontal",'spalab'))
						),array(
							"id"=>		"delicious",
							"label"=>	__("Show Delicious",'spalab'),
							"text"=>""
						),array(
							"id"=>		"twitter",
							"label"=>	__("Show Twitter",'spalab'),
							"options"=>	array(
								"none" => __("None",'spalab'),
								"vertical" => __("Vertical",'spalab')
								,"horizontal"=>__("Horizontal",'spalab')),
							"username"=>'',
							"lang"=>	array(
							    ""	 => __("Select",'spalab'),
								"fr" => __( "French",'spalab' ),
								"de" => __( "German",'spalab' ),
								"it" => __( "Italian",'spalab' ),
								"ja" => __( "Japanese",'spalab' ),
								"ko" => __( "Korean",'spalab' ),
								"ru" => __( "Russian",'spalab' ),
								"es" => __( "Spanish",'spalab' ),
								"tr" => __( "Turkish",'spalab' ))
						));?>